account/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "account"

urlpatterns = [
    path('register/', views.registration_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('account/', views.account_view, name="account"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('deleteuser/', views.delete_user, name="delete_user"),



]

article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [

    path('detail/<int:id>', views.detail, name="detail"),
    path('', views.articles, name="articles"),
    path('comment/<int:id>', views.addComment, name="comment"),
    path('like/<int:id>', views.like_post_article, name="like_post"),
    path('favourite_post/<int:id>', views.favourite_post, name="favourite_post"),
    path('favourite_list/', views.favourite_list, name="favourite_list"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account import views
import article
from news import views
from article import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('sendArticle/', views.sendArticle, name="sendArticle"),
    path('news/', include("news.urls")),
    path('journals/', include("journals.urls")),
    path('articles/', include("article.urls")),
    path('account/', include("account.urls")),
    path('ckeditor', include("ckeditor_uploader.urls")),
    path('interviews/', include("interviews.urls")),





    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = article.views.handler404
handler500 = article.views.handler500

journals/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "journals"

urlpatterns = [


    path('', views.journals, name="journals"),




]

news/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "news"

urlpatterns = [


    path('', views.news, name="news"),
    path('detail/<int:id>', views.detail, name="detail"),
    path('like/<int:id>', views.like_post_news, name="like_post"),
    path('comment/<int:id>', views.addComment, name="comment"),
    path('favourite_post/<int:id>', views.favourite_post, name="favourite_post"),

    # path('comment/<int:id>',views.addComment,name = "comment"),

]

templates/includes/footer.html
<footer>
    <div class="outer">
        <!--   <div class="bottom">
            <a href="#">Hakkımızda</a>
            <a href="#">İletişim</a>
        </div> -->
        <small>Akdeniz Üniversitesi Bilgisayar Topluluğu Tarafından Hazırlanmıştır</small>
    </div>
</footer>

templates/includes/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">


<nav class="navbar sticky-top navbar-expand-lg ">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index'  %}"><img style="height: 40px; width: 150px"
                src="{% static 'image/LogoDergi.png' %}" alt=""></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">

            <span class="material-icons" style="cursor: pointer; color: white;">
                table_rows
            </span>
        </button>
        <div class="collapse navbar-collapse nav-elements" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'journals:journals' %}">Dergiler</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'article:articles' %}">
                        Makaleler
                    </a>

                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'news:news' %}">Haberler</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'interviews:interviews' %}">Roportajlar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sendArticle' %}">Makale Gönder</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">Hakkımızda</a>
                </li>
            </ul>


            <ul class="navbar-nav">
                <form class="d-flex" id="seacrh">
                    {% csrf_token %}
                    <span class="material-icons" style="cursor: pointer; color: white;" id="searchbtn" role="button">
                        search
                    </span>
                    <div class="hide" id="searchInput">
                        <input type="text" name="keyword" style="border-radius: 40px;">
                    </div>

                </form>

                <li class="dropdown profile nav-item">
                    <span class="material-icons nav-link dropdown-toggle" style="cursor: pointer; color: white;"
                        id="profile" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        account_circle
                    </span>
                    <ul class="dropdown-menu" aria-labelledby="profile">
                        {% if request.user.is_authenticated %}
                        <li><a class="dropdown-item" href="{% url 'article:favourite_list' %}">Favorilerim</a></li>
                        <li><a class="dropdown-item" href="{% url 'account:account' %}">Bilgilerimi Güncelle</a></li>
                        <li><a class="dropdown-item" href="{% url 'password_change' %}">Şifremi Değiştir</a></li>
                        <li><a class="dropdown-item" href="{% url 'account:logout' %}">Çıkış</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{% url 'account:login' %}">Giriş Yap</a></li>

                        <li><a class="dropdown-item" href="{% url 'account:register' %}">Üye Ol</a></li>

                        {% endif %}

                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- navbar end -->