account/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "account"

urlpatterns = [
    path('register/', views.registration_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('account/', views.account_view, name="account"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('deleteuser/', views.delete_user, name="delete_user"),



]

article/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [

    path('detail/<int:id>', views.detail, name="detail"),
    path('', views.articles, name="articles"),
    path('comment/<int:id>', views.addComment, name="comment"),
    path('like/<int:id>', views.like_post_article, name="like_post"),
    path('favourite_post/<int:id>', views.favourite_post, name="favourite_post"),
    path('favourite_list/', views.favourite_list, name="favourite_list"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account import views
import article
from news import views
from article import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('sendArticle/', views.sendArticle, name="sendArticle"),
    path('news/', include("news.urls")),
    path('journals/', include("journals.urls")),
    path('articles/', include("article.urls")),
    path('account/', include("account.urls")),
    path('ckeditor', include("ckeditor_uploader.urls")),
    path('interviews/', include("interviews.urls")),





    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = article.views.handler404
handler500 = article.views.handler500

journals/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "journals"

urlpatterns = [


    path('', views.journals, name="journals"),




]

news/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "news"

urlpatterns = [


    path('', views.news, name="news"),
    path('detail/<int:id>', views.detail, name="detail"),
    path('like/<int:id>', views.like_post_news, name="like_post"),
    path('comment/<int:id>', views.addComment, name="comment"),
    path('favourite_post/<int:id>', views.favourite_post, name="favourite_post"),

    # path('comment/<int:id>',views.addComment,name = "comment"),

]

journals/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.shortcuts import reverse
# Create your models here.


class Journals(models.Model):

    author = models.ForeignKey(
        "account.Account", on_delete=models.CASCADE, verbose_name="Yazar")
    title = models.CharField(max_length=50, verbose_name="Başlık")
    journals_file = models.FileField(
        blank=True, null=True, verbose_name="Derginin Dosyasını Ekleyiniz")
    created_date = models.DateTimeField(
        auto_now_add=True, verbose_name="Oluşturulma Tarihi")
    journals_image = models.FileField(
        blank=True, null=True, verbose_name="Dergiye Kapak Fotoğraf Ekleyiniz.")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django.db.models import fields


from account.models import Account


class RegistrationForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = Account
        fields = ("email", "fullName", "password1", "password2",
                  "universty", "department", "account_type")


class AccountAuthenticationForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = Account
        fields = ('email', 'password')

    def clean(self):

        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']

            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Giriş Başarısız.")


class AccountUptadeForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('email', 'fullName', 'universty',
                  'department', 'account_type', 'account_avatar')

        def clean_email(self):
            email = self.cleaned_data['email']
            fullName = self.cleaned_data['fullName']
            universty = self.cleaned_data['University']
            department = self.cleaned_data['Department']
            account_type = self.cleaned_data['account_type']
            account_avatar = self.cleaned_data['account_avatar']
            try:
                account = Account.objects.exclude(
                    pk=self.instance.pk).get(email=email)
            except Account.DoesNotExist:
                return email
            raise forms.ValidationError('Bu Email "%s" kullanılıyor' % account)


class UserDeleteForm(forms.ModelForm):

    class Meta:
        model = Account

        fields = []

article/forms.py
from django import forms
from .models import Article, sendArticle


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "article_image"]


class ArticleSend(forms.ModelForm):

    class Meta:
        model = sendArticle
        fields = ["name", "email", "article_file", "article_image"]

journals/forms.py
from django import forms
from .models import Journals


class JournalsForm(forms.ModelForm):
    class Meta:
        model = Journals
        fields = ["title", "content", "journals_image"]

news/forms.py
from django import forms
from .models import News
class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ["title","content","news_image"]

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse, HttpResponseRedirect
from .forms import ArticleForm, ArticleSend
from .models import Article, Comment, sendArticle
import datetime
from django.contrib import messages
from django.conf import settings
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
# Create your views here.


def articles(request):
    keyword = request.GET.get("keyword")
    keyword_category = request.GET.get("keyword_category")

    print(keyword_category)

    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request, "articles.html", {"articles": articles})

    if keyword_category:
        articles = Article.objects.filter(
            article_category__contains=keyword_category)
        return render(request, "articles.html", {"articles": articles})

    articles = Article.objects.all()

    context = {
        "articles": articles,

    }
    return render(request, "articles.html", context)


def index(request):

    keyword = request.GET.get("keyword")

    keyword_category = request.GET.get("keyword_category")

    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request, "articles.html", {"articles": articles})

    if keyword_category:
        articles = Article.objects.filter(
            article_category__contains=keyword_category)

        return render(request, "articles.html", {"articles": articles})

    week_ago = datetime.date.today() - datetime.timedelta(days=45)
    trends = Article.objects.filter(
        created_date__gte=week_ago).order_by('-read')

    carousel_item1 = Article.objects.filter(
        article_category__contains='Yapay Zeka')[:1]

    carousel_item2 = Article.objects.filter(
        article_category__contains='Yazılım')[:1]

    carousel_item3 = Article.objects.filter(
        article_category__contains='Donanım')[:1]

    carousel_item4 = Article.objects.filter(
        article_category__contains='Kripto Para')[:1]

    articles = Article.objects.all()

    context = {
        'trends': trends[:5],
        'articles': articles,
        'carousel_item1': carousel_item1,
        'carousel_item2': carousel_item2,
        'carousel_item3': carousel_item3,
        'carousel_item4': carousel_item4,

    }

    return render(request, "index.html", context)


def about(request):
    return render(request, "about.html")


def detail(request, id):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request, "articles.html", {"articles": articles})

    article = get_object_or_404(Article, id=id)

    current_detail = article

    url = "http://localhost:8000" + article.get_absolute_url()

    print(url)

    week_ago = datetime.date.today() - datetime.timedelta(days=45)

    sideArticle = Article.objects.filter(created_date__gte=week_ago).order_by(
        '-read').exclude(title=current_detail)[:3]

    article = get_object_or_404(Article, id=id)

    article.read += 1

    article.save()

    is_liked = False
    is_favourite = False

    if article.likes.filter(id=request.user.id):
        is_liked = True

    if article.favourite.filter(id=request.user.id):
        is_favourite = True

    comments = article.comments.all()

    context = {
        'article': article,
        'comments': comments,
        'is_liked': is_liked,
        'total_likes': article.total_likes(),
        'is_favourite': is_favourite,
        'sideArticle': sideArticle,
        'url': url

    }
    return render(request, "detail.html", context)


@login_required(login_url="account:login")
def addComment(request, id):
    article = get_object_or_404(Article, id=id)

    if request.method == "POST":
        comment_author = request.user.fullName
        comment_content = request.POST.get("comment_content")
        comment_photo = request.user.account_avatar

        newComment = Comment(comment_author=comment_author,
                             comment_content=comment_content,
                             comment_photo=comment_photo)

        newComment.article = article

        newComment.save()
    return redirect(reverse("article:detail", kwargs={"id": id}))


@login_required(login_url="account:login")
def like_post_article(request, id):

    post = get_object_or_404(Article, id=id)

    is_liked = False

    if post.likes.filter(id=request.user.id):
        post.likes.remove(request.user)
        is_liked = False

    else:
        post.likes.add(request.user)
        is_liked = True

    return HttpResponseRedirect(post.get_absolute_url())


@login_required(login_url="account:login")
def favourite_post(request, id):

    post = get_object_or_404(Article, id=id)

    if post.favourite.filter(id=request.user.id):
        post.favourite.remove(request.user)
    else:
        post.favourite.add(request.user)

    return HttpResponseRedirect(post.get_absolute_url())


def favourite_list(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request, "articles.html", {"articles": articles})
    user = request.user

    favourite_posts = user.favourite.all()

    context = {
        'favourite_posts': favourite_posts
    }

    return render(request, "favourites.html", context)


def sendArticle(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request, "articles.html", {"articles": articles})

    name = request.POST.get('name', '')
    post_type = request.POST.get('accType', '')
    subject = name + \
        " İsimli Kullanıcının Gönderisi, Gönderi Tipi : " + post_type
    message = request.POST.get('message', '')

    basemail = 'batuhannbagg@gmail.com'

    sendmail = EmailMessage(

        subject,
        message,
        settings.EMAIL_HOST_USER,
        [basemail]

    )
    if request.method == "GET":
        return render(request, "sendArticle.html")
    else:
        file = request.FILES['file']

    if request.user.is_authenticated == True:

        sendmail.attach(file.name, file.read(), file.content_type)
        print(file, subject, message, post_type)
        sendmail.send()
        return render(request, "sendArticle_OK.html")
    else:
        messages.info(
            request, 'Lütfen işlemi gerçekleştirmek için giriş yapınız.')
        return render(request, "sendArticle.html")


def handler404(request):
    return render(request, '404page.html', status=404)


def handler500(request):
    return render(request, '404page.html', status=500)

journals/views.py
from article.models import Article
from django.db import models
from django.shortcuts import render
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse, HttpResponseRedirect
from .models import Journals
from django.contrib.auth.decorators import login_required


def journals(request):

    journals = Journals.objects.all()

    return render(request, "journals.html", {"journals": journals})

news/views.py
from django.shortcuts import render
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse, HttpResponseRedirect
from .models import News, Comment
import datetime
from django.contrib.auth.decorators import login_required


def detail(request, id):

    news = get_object_or_404(News, id=id)

    current_detail = news

    week_ago = datetime.date.today() - datetime.timedelta(days=45)

    sideNews = News.objects.filter(created_date__gte=week_ago).order_by(
        '-read').exclude(title=current_detail)[:3]

    news.read += 1

    news.save()

    is_liked = False
    is_favourite = False

    if news.likes.filter(id=request.user.id):
        is_liked = True

    if news.favourite_news.filter(id=request.user.id):
        is_favourite = True

    comments = news.comments.all()

    context = {
        'news': news,
        'comments': comments,
        'is_liked': is_liked,
        'total_likes': news.total_likes(),
        'is_favourite': is_favourite,
        'sideNews': sideNews,

    }
    return render(request, "newsDetail.html", context)


@login_required(login_url="account:login")
def like_post_news(request, id):

    post = get_object_or_404(News, id=request.POST.get('post_id'))

    is_liked = False

    if post.likes.filter(id=request.user.id):
        post.likes.remove(request.user)
        is_liked = False

    else:
        post.likes.add(request.user)
        is_liked = True

    return HttpResponseRedirect(post.get_absolute_url())


login_required(login_url="account:login")


def favourite_post(request, id):

    post = get_object_or_404(News, id=id)

    if post.favourite_news.filter(id=request.user.id):
        post.favourite_news.remove(request.user)
    else:
        post.favourite_news.add(request.user)

    return HttpResponseRedirect(post.get_absolute_url())


@login_required(login_url="account:login")
def addComment(request, id):
    news = get_object_or_404(News, id=id)

    if request.method == "POST":
        comment_author = request.user.fullName
        comment_content = request.POST.get("comment_content")
        comment_photo = request.user.account_avatar

        newComment = Comment(comment_author=comment_author,
                             comment_content=comment_content,
                             comment_photo=comment_photo)

        newComment.news = news

        newComment.save()
    return redirect(reverse("news:detail", kwargs={"id": id}))


def news(request):

    news = News.objects.all()
    return render(request, "news.html", {"news": news})


def about(request):
    return render(request, "about.html")

templates/404page.html
{% extends 'layout.html' %}
{% load static %}


{% block body %}

<style>
    .background {
        background: url("{% static 'image/akdeniz.jpg' %}") no-repeat center center fixed #000;
        background-repeat: no-repeat;
        background-size: cover;

        pointer-events: none;
        position: fixed;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        z-index: -1;

    }
</style>
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/404.css' %}">

<div class="container">


    <div class="wrapError">
        <h1 class="ErrorHeader">
            404
        </h1>
        <p class="ErrorMessage">
            Aradığınız Sayfa Bulunamadı.
        </p>
    </div>


    <div class="background">
        <!-- <img src="../images/akdeniz.jpg" alt=""> -->

    </div>

</div>


{% endblock body %}

templates/db.html
{% extends 'layout.html' %}


{% block body %}

<style type="text/css">
    .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
    }

    .form-signin .checkbox {
        font-weight: 400;
    }

    .form-signin .form-control {
        position: relative;
        box-sizing: border-box;
        height: auto;
        padding: 10px;
        font-size: 16px;
    }

    .form-signin .form-control:focus {
        z-index: 2;
    }

    .form-signin input[type="email"] {
        margin-bottom: 10px;
        border-bottom-right-radius: 0;
        border-bottom-left-radius: 0;
    }

    .h3 {
        text-align: center;
    }
</style>


<form method="POST" class="form-signin">{% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">Reset password</h1>
    <input name="email" class="form-control" placeholder="Email address" type="email" id="id_email" required autofocus
        value={{ user.email }}>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Send reset email</button>
</form>



{% endblock %}

templates/is_active.html
{% extends 'layout.html' %}
{% block body %}

<div class="container">

    <h3> Hesabınız Aktive Edilmiştir İyi Okumalar Dileriz. </h3>
    <small> Akdeniz Üniversitesi Bilişim Dergi </small>

</div>


{% endblock body %}

templates/login.html
{% extends "layout.html" %}
{% load static %}

{% block body %}
<link rel="stylesheet" href="{% static 'css/navbar.css' %}">
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
<link rel="stylesheet" href="{% static 'css/profile.css' %}">



<div class="container">
  <div class="profilePage">

    <h5 style="text-align: center; font-weight: bold;">GİRİŞ YAP</h5>

    <div>
      <form method="POST">
        {% csrf_token %}
        <div class="form">
          <input required type="email" name="email" placeholder="E-posta adresi">
          <input required type="password" name="password" placeholder="Şifre giriniz">

          <div style="display: flex; justify-content: space-between;">

            <label class="check">
              <p> Beni Hatırla</p>
              <input type="checkbox" value="lsRememberMe" id="rememberMe" />
              <span class="checkbox"></span>
            </label>
            <a class="forget" href="{% url 'password_reset' %}">Şifremi Unuttum!</a>
          </div>

        </div>
        <div style="display: flex; align-items:baseline">
          <div>
            {% for field in login_form %}
            <p>
              {% for error in field.errors %}
            <p style="color: rgb(255, 145, 0)">{{ error }}</p>
            {% endfor %}
            </p>
            {% endfor %}
            {% if login_form.non_field_errors %}
            <div style="color: rgb(255, 145, 0)">
              <p>{{login_form.non_field_errors}}</p>
            </div>

            {% endif %}
          </div>
          <input type="submit" onclick="lsRememberMe()" value="Giriş Yap" class="btn right">
        </div>
      </form>
      <div class="contentFooter">

        <p>Hesabın Yok Mu? <a href="{% url 'account:register' %}">Kaydol</a></p>


      </div>
    </div>
  </div>
</div>

<script>
  const rmCheck = document.getElementById("rememberMe"),
    emailInput = document.getElementById("email");



  if (localStorage.checkbox && localStorage.checkbox !== "") {
    rmCheck.setAttribute("checked", "checked");
    emailInput.value = localStorage.username;
  } else {
    rmCheck.removeAttribute("checked");
    emailInput.value = "";
  }

  function lsRememberMe() {

    if (rmCheck.checked && emailInput.value !== "") {

      localStorage.username = emailInput.value;
      localStorage.checkbox = rmCheck.value;
    } else {

      localStorage.username = "";
      localStorage.checkbox = "";
    }
  }
</script>
{% endblock body %}

templates/newsDetail.html
{% extends "layout.html" %} {% load static %} {% block body %}

<link rel="stylesheet" href="{% static 'css/footer.css' %}" />
<link rel="stylesheet" href="{% static 'css/socialMedia.css' %}" />
<link rel="stylesheet" href="{% static 'css/ContentDetail.css' %}" />
<link rel="stylesheet" href="{% static 'css/navbar.css' %}" />

<div class="container mb-5">
    <div class="row">
        <!-- Content -->
        <section class="col-md-9" id="left">
            <article class="contents">
                <div class="contentHeader">
                    <h3>{{news.title}}</h3>

                    <time>{{news.created_date}}</time>
                    <p>{{news.author.fullName}}</p>
                </div>
                <div class="row">
                    <div class="col-md-1 hideLeftLike">
                        <div class="contentLike leftContentLike">
                            <form method="POST" id="like">
                                {% csrf_token %}
                                <button style="cursor: pointer" id="likeButton" type="submit" name="post_id"
                                    value="{{news.id}}">
                                    <i id="icon" class="far fa-thumbs-up fa-lg"></i>
                                </button>
                            </form>
                            <form method="POST" id="favourite">
                                <button type="submit">
                                    <i class="far fa-bookmark fa-lg" id="favourite_icon"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="article col-md-11">
                        <div class="my-3" style="width: 100%">
                            <img width="100%" height="400px" src="{{news.news_image.url}}" />
                        </div>

                        <p>{{news.content|safe}}</p>


                        <p style="margin-top: 5%">
                            Bu röportaj {{ news.read }} defa görüntülenmiştir.
                        </p>

                        <div class="contentBottom">
                            <div class="contentInteraction">
                                <div class="contentLike hideContentLike">
                                    <form id="like">
                                        {% csrf_token %}
                                        <button style="cursor: pointer" id="likeButton" type="submit" name="post_id"
                                            value="{{news.id}}">
                                            <i id="icon" class="far fa-thumbs-up fa-lg"></i>
                                        </button>
                                    </form>
                                    <form method="POST" id="favourite">
                                        <button type="submit">
                                            <i class="far fa-bookmark fa-lg" id="favourite_icon"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>

                            <div>
                                <a href="https://www.linkedin.com/feed/" target="_blank">

                                    <button class="linkedin">

                                        <i style="color: white" class="fab fa-linkedin-in"></i>
                                    </button>
                                </a>
                                <a href="https://www.facebook.com/" target="_blank">
                                    <button class="facebook">
                                        <i style="color: white" class="fab fa-facebook-f"></i>
                                    </button>
                                </a>
                                <a href="whatsapp://send?text={{url}}">
                                    <button class="whatsapp">
                                        <i style="color: white" class="fab fa-whatsapp"></i>
                                    </button>
                                </a>
                            </div>
                        </div>

                        <div class="commentForce">
                            {% if request.user.is_authenticated %}
                            <h5>Yorum yaz</h5>

                            {% else %}
                            <p>
                                yorum yapmak için
                                <a href="{% url 'account:login' %}">giriş</a> yapmalısınız
                            </p>
                            {% endif %}
                        </div>

                        {% if request.user.is_authenticated %}
                        <form class="writeCommentwrap" action="{% url 'news:comment'  news.id %}" method="post">
                            {% csrf_token %}
                            <div class="writeComment">
                                <textarea name="comment_content" placeholder="Yorum Yaz..." cols="103"
                                    rows="5"></textarea>
                            </div>

                            <button type="submit" class="btn right">Yorum Yap</button>
                        </form>
                        {% endif %} {% if comments %} {% for comment in comments %}
                        <div class="commentsPart">
                            {% if comment.comment_photo %}
                            <img src="{{comment.comment_photo.url}}" alt="avatar" />
                            {% else %}
                            <img src="{% static 'image/akdenız_logo.png' %}" alt="avatar" />
                            {% endif %}
                            <div class="commentsPartright">
                                <div>
                                    <h6>{{comment.comment_author}}</h6>
                                    <time> {{comment.comment_date}} </time>
                                </div>
                                <p>{{comment.comment_content}}</p>
                            </div>
                        </div>
                        {% endfor %} {% else %}

                        <div class="commentsPart">
                            <div class="commentsPartright">
                                <div style="margin-top: 3%">
                                    Bu röportaja yorum yapılmamıştır.İlk yorumu yapan siz olun!
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </article>
        </section>

        <!-- side start -->
        <section class="col-md-3" id="right">
            <div>
                <h5 style="color: #ff914d; font-weight:bold">Bizi Takip Et</h5>
                <div class="socialmediaButtons">
                    <a href="https://twitter.com/btakdenizuni" target="_blank">
                        <button class="twitter">
                            <i style="color: white" class="fab fa-twitter"></i>
                            Twitter
                        </button>
                    </a>
                    <a href="https://www.instagram.com/btakdenizuni/" target="_blank">
                        <button class="instagram">
                            <i style="color: white" class="fab fa-instagram"></i>
                            İnstagram
                        </button>
                    </a>
                </div>
            </div>
            <h5 style="color: #ff914d; font-weight: bold">Beğenebilecekleriniz</h5>
            {% for side in sideNews %}
            <div>
                <a class="contentRight" style="text-decoration-color: #ff914d;" href="{% url 'news:detail' side.id %}">
                    <img src="{{side.news_image.url}}" alt="content" style="border-radius: 30px; margin-bottom: 5%" />
                    <h6 style="color:#ff914d;font-weight:bold">{{ side.title }}</h6>
                </a>
            </div>
            {% endfor %}
        </section>
    </div>
</div>
<!-- footer start -->

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
    crossorigin="anonymous"></script>

<script type="text/javascript">
    $(document).on("submit", "#like", function (e) {
        console.log($("input[name=csrfmiddlewaretoken]").val());
        e.preventDefault();

        $.post(
            '{% url "news:like_post" news.id  %}',
            {
                post_id: $("#likeButton").val(),
                csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
            },
            function (data, success) {
                const id = document.getElementById("icon");
                if (id.classList.contains("fas")) {
                    id.classList.remove("fas");
                    id.classList.toggle("far");
                } else if (id.classList.contains("far")) {
                    id.classList.toggle("fas");
                    id.classList.remove("far");
                }
            }
        );
    });
</script>

<script type="text/javascript">
    $(document).on("submit", "#favourite", function (e) {
        e.preventDefault();

        $.post(
            "{% url 'news:favourite_post' news.id %}",
            {
                csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
            },
            function (data, success) {
                console.log("success");
                const id = document.getElementById("favourite_icon");
                if (id.classList.contains("fas")) {
                    id.classList.remove("fas");
                    id.classList.toggle("far");
                } else if (id.classList.contains("far")) {
                    id.classList.toggle("fas");
                    id.classList.remove("far");
                }
            }
        );
    });
</script>

{% endblock body %}